dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0'

dotenv: .env

params:
  callbackGasLimit: 200000 # default is 100000, each word storage cost aprox 20000
  requestConfirmations: 3 #default
  subscriptionId: ${SUBSCRIPTION_ID} # 0 for programmatic subscription

networks:
  default: development
  development: # no necesita eth_usd_price_feed, vrf_coordinator o link_token_contract por el mock
    key_hash: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15" #30 gwei, same goerli key_hash
    verify: False
  ganache-local:
    verify: False
  mainnet-fork-dev:
    cmd_settings:
      unlock:
        - 0xf37c348b7d19b17b29cd5cfa64cfa48e2d6eb8db # create an account with large LINK balance

    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    vrf_coordinator: "0x271682deb8c4e0901d1a1550ad2e64d568e69909"
    key_hash: "0xff8dedfbfa60af186cf3c830acbc32c05aae823045ae5ea7da1e45fbfaba4f92" # 500 gwei
    link_token_contract: "0x514910771af9ca656af840dff83e8264ecf986ca"
    verify: False
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    vrf_coordinator: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D"
    key_hash: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15" #30 gwei
    link_token_contract: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    verify: False
wallets:
  account_name: "metamask_1"
